variables:
   ACE_ROOT: $(Build.SourcesDirectory)/ACE
   TAO_ROOT: $(Build.SourcesDirectory)/TAO
   MPC_ROOT: $(Build.SourcesDirectory)/ACE/MPC
   system.prefergit: true

schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
- repo: self
  fetchDepth: 1

jobs:
- job: VisualStudio2019
  timeoutInMinutes: 120
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      WChar:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: 'openssl xerces-c[xmlch_wchar]'
        OptionalFeatures: uses_wchar=1
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: openssl xerces-c
      Release64:
        BuildPlatform: x64
        BuildConfiguration: Release
        vcpkgarch: x64-windows
        vcpkglibdir: lib
        vcpkgpackages: openssl xerces-c
      Debug32:
        BuildPlatform: Win32
        BuildConfiguration: Debug
        vcpkgarch: x86-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: openssl xerces-c
      Release32:
        BuildPlatform: Win32
        BuildConfiguration: Release
        vcpkgarch: x86-windows
        vcpkglibdir: lib
        vcpkgpackages: openssl xerces-c
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESC_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    XERCESC_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    SSL_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    SSL_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone -q --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg install --recurse --triplet $(vcpkgarch) $(vcpkgpackages)
    displayName: Install additional packages using vcpkg
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "openssl11=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "versioned_namespace=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: |
      echo $(OptionalFeatures) | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Add optional features ($(OptionalFeatures))
    condition: and(succeeded(), ne(variables['OptionalFeatures'], ''))
  - powershell: git clone -q --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2019 $(TAO_ROOT)/TAO_ACE.mwc -workers 4
    displayName: Run script mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2019 $(ACE_ROOT)/tests/tests.mwc -workers 4
    displayName: Run script mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - task: VSBuild@1
    displayName: Build solution TAO/TAO_ACE.sln
    inputs:
      solution: TAO/TAO_ACE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true
  - task: VSBuild@1
    displayName: Build solution ACE/tests/tests.sln
    inputs:
      solution: ACE/tests/tests.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: VisualStudio2017
  timeoutInMinutes: 120
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      WChar:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: 'openssl xerces-c[xmlch_wchar]'
        OptionalFeatures: uses_wchar=1
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: openssl xerces-c
      Release64:
        BuildPlatform: x64
        BuildConfiguration: Release
        vcpkgarch: x64-windows
        vcpkglibdir: lib
        vcpkgpackages: openssl xerces-c
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESC_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    XERCESC_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    SSL_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    SSL_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg install --recurse --triplet $(vcpkgarch) $(vcpkgpackages)
    displayName: Install additional packages using vcpkg
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "openssl11=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "versioned_namespace=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ipv6=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: |
      echo $(OptionalFeatures) | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Add optional features ($(OptionalFeatures))
    condition: and(succeeded(), ne(variables['OptionalFeatures'], ''))
  - powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2017 $(TAO_ROOT)/TAO_ACE.mwc -workers 4
    displayName: Run script mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2017 $(ACE_ROOT)/tests/tests.mwc -workers 4
    displayName: Run script mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - task: VSBuild@1
    displayName: Build solution TAO/TAO_ACE.sln
    inputs:
      solution: TAO/TAO_ACE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true
  - task: VSBuild@1
    displayName: Build solution ACE/tests/tests.sln
    inputs:
      solution: ACE/tests/tests.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: Linux
  timeoutInMinutes: 90
  strategy:
    matrix:
      CLANG5:
        imagename: ubuntu-16.04
        CC: clang-5.0
        CXX: clang++-5.0
        PackageDeps: clang-5.0
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
      CLANG6:
        imagename: ubuntu-18.04
        CC: clang-6.0
        CXX: clang++-6.0
        PackageDeps: clang-6.0
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
      CLANG7:
        imagename: ubuntu-18.04
        CC: clang-7
        CXX: clang++-7
        PackageDeps: clang-7
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
      CLANG8:
        imagename: ubuntu-18.04
        CC: clang-8
        CXX: clang++-8
        PackageDeps: clang-8
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
      CLANG9:
        imagename: ubuntu-18.04
        CC: clang-9
        CXX: clang++-9
        PackageDeps: clang-9
        Repo: llvm-toolchain-$(lsb_release -cs)-9
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
      CLANG10:
        imagename: ubuntu-18.04
        CC: clang-10
        CXX: clang++-10
        PackageDeps: clang-10
        Repo: llvm-toolchain-$(lsb_release -cs)-10
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU
  pool:
    vmImage: $(imagename)
  steps:
  - script: |
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $(Repo) main"
    displayName: Add repository ($(Repo))
    condition: and(succeeded(), ne(variables['Repo'], ''))
  - script: |
      sudo apt-get --yes update
      sudo apt-get --yes install libxerces-c-dev libssl-dev $(PackageDeps)
    displayName: install system package dependencies
  - powershell: |
      '#include "ace/config-linux.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'xerces3=1' > $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'ssl=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'ipv6=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'versioned_namespace=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
    displayName: Create default.features file
  - powershell: |
      'xerces3=1' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'ssl=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'ipv6=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      "$(platform_file)" >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
    displayName: Create platform_macros file
  - powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(TAO_ROOT)/TAO_ACE.mwc -workers 4
    displayName: Run mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(ACE_ROOT)/tests/tests.mwc -workers 4
    displayName: Run mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - bash: make -j 6 -C TAO
    displayName: Build TAO project
  - bash: make -j 6 -C ACE/tests
    displayName: Build tests project

- job: MacOSX
  timeoutInMinutes: 90
  pool:
    vmImage: macOS-latest
  steps:
  - powershell: |
      '#include "ace/config-macosx.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'include $(ACE_ROOT)/include/makeinclude/platform_macosx.GNU' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU;
    displayName: Create platform_macros file
  - powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(MPC_ROOT)
    displayName: git clone MPC
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(TAO_ROOT)/TAO_ACE.mwc -workers 4
    displayName: Run mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(ACE_ROOT)/tests/tests.mwc -workers 4
    displayName: Run mwc.pl on $(ACE_ROOT)/tests/tests.mwc
  - bash: make -j 6 -C TAO
    displayName: Build TAO project
  - bash: make -j 6 -C ACE/tests
    displayName: Build tests project
