name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACE_ROOT: ${GITHUB_WORKSPACE}/ACE
      TAO_ROOT: ${GITHUB_WORKSPACE}/TAO
      MPC_ROOT: ${GITHUB_WORKSPACE}/MPC
          
    steps:
    - name: checkout ACE/TAO
      uses: actions/checkout@v1
    - name: checkout MPC
      uses: actions/checkout@v1
      with:
        repository: DOCGroup/MPC
        ref: master
        fetch-depth: 1
    - name: create $ACE_ROOT/ace/config.h
      run: |
        echo ${env:ACE_ROOT}
        echo ${env:GITHUB_WORKSPACE}
        '#include "ace/config-win32.h"' > ${env:GITHUB_WORKSPACE}/ACE/ace/config.h
      shell: pwsh
    - name: create $ACE_ROOT/include/makeinclude/platform_macros.GNU
      run: |
        'include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU' >  ${env:GITHUB_WORKSPACE}/ACE/include/makeinclude/platform_macros.GNU
      shell: pwsh
    - name: Run mwc.pl on $(TAO_ROOT)/TAO_ACE.mwc
      run: | 
        perl ${env:ACE_ROOT}/bin/mwc.pl -type gnuace ${env:GITHUB_WORKSPACE}/TAO/TAO_ACE.mwc -workers 4
      shell: pwsh
    - name: Build TAO project
      run: |
        make -j 6 -C ${env:GITHUB_WORKSPACE}/TAO
    
    
